### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by b-yp** [chiimagnus/logseq-AIsearch#1]
![image](https://github.com/user-attachments/assets/804275eb-5ec1-4af0-ab0f-de3545fc813f)

这是我之前想写插件的思路，今天发现你已经写了，我看了一下你的代码，和我的思路基本一致
我觉得可以先查询 tag 然后结合搜索内容来提高搜索相关度

**Comment by chiimagnus** [comment]
@b-yp 
1、首先非常感谢你提的建议❤️，很高兴有人能回应啊！
2、你说到的先检索tag，对我来说哈，可能我打tag的时候不会很精细，所以不太会使用tag。不过后续我开发会考虑你提的这个建议，我会衡量一下。
3、说到相关度，其实我让AI做了相关度函数，在utils文件里，我自己测试的时候感觉相关度还行，至少是在回应我的内容。
4、AI在提炼关键词的时候，目前还只能分解关键词，我希望后续做出「关键词延伸」功能，这样能检索的东西就会更多。一定程度会提高相关性。
5、有一个难题我还没有解决，因为检索的时候可能是关键词一次被检索，所以返回给AI的数据会很大，我现在的想法是加一层「过滤功能」，差不多就是套用一层「相关度函数」吧。

另外，非常期待你的使用体验反馈！

**Comment by b-yp** [comment]
你可以在微信搜公众号 “李继刚” 或者 即刻 App 搜 “李继刚”
他是一个把 AI 玩出花来的人，他用写 lisp 代码的方式写 prompt
![802895c25e42c61e242441ec42d9651e](https://github.com/user-attachments/assets/20ff0390-245a-4de4-8ed6-035cb3435572)

**Comment by chiimagnus** [comment]
> 你可以在微信搜公众号 “李继刚” 或者 即刻 App 搜 “李继刚”
> 
> 他是一个把 AI 玩出花来的人，他用写 lisp 代码的方式写 prompt
> 
> ![802895c25e42c61e242441ec42d9651e](https://github.com/user-attachments/assets/20ff0390-245a-4de4-8ed6-035cb3435572)
> 
> 

谢谢啦😘
